// <auto-generated />
using Back;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240109081314_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttacksPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDieMultiplier")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDieSides")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 14,
                            AttackModifier = 8,
                            AttacksPerRound = 2,
                            DamageDieMultiplier = 1,
                            DamageDieSides = 6,
                            DamageModifier = 4,
                            HitPoints = 52,
                            Name = "Bonnie"
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 12,
                            AttackModifier = 10,
                            AttacksPerRound = 2,
                            DamageDieMultiplier = 3,
                            DamageDieSides = 10,
                            DamageModifier = 4,
                            HitPoints = 91,
                            Name = "Ashann"
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 11,
                            AttackModifier = 4,
                            AttacksPerRound = 1,
                            DamageDieMultiplier = 1,
                            DamageDieSides = 4,
                            DamageModifier = 0,
                            HitPoints = 22,
                            Name = "Dryad"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
